faq: cont'd #40
OpenDataforWeb3/Resources pull request #100
Opened 2023-01-28 14:11 UTC by owanikin

Implements issue #40

2023-01-30 16:40 UTC, epowell101 commented on docs/faq.md
> +Yes, absolutely. It just have to be really good!
"It just has to be really good." as opposed to be it HAVE to be really good

2023-01-30 16:41 UTC, epowell101 requested changes
See minor comment HAVE vs. HAS

2023-01-31 01:29 UTC, sarob approved these changes
Looks good.

2023-01-31 01:30 UTC, sarob approved these changes
accepted

2023-01-31 01:32 UTC, merged